_target_: taowm.models.critic.critic.Critic
_recursive_: false
perceptual_features: ???
action_features: ???
latent_goal_features: ${model.visual_goal.latent_goal_features}
hidden_features: 256
num_layers: 3
num_critics: 2
activation: ReLU