defaults:
  - perceptual_encoder: rgb_static_gripper
  - visual_goal: default
  - action_decoder: hulc_default
  - optimizer: adam
  - lr_scheduler: constant

_target_: taowm.models.gcbc.GCBC
_recursive_: false

state_recons: false
state_recon_beta: ${loss.state_recon_beta}
