defaults:
  - perceptual_encoder: rgb_static_gripper
  - plan_proposal: default
  - plan_recognition: transformers
  - distribution: continuous_tanhnormal
  - visual_goal: default
  - action_decoder: hulc_default
  - critic: default
  - optimizer: adam
  - lr_scheduler: constant

_target_: taowm.models.tacorl.TACORL
_recursive_: false

replan_freq: 15
kl_beta: ${loss.kl_beta}
kl_balancing_mix: ${loss.kl_balancing_mix}
state_recons: false
state_recon_beta: ${loss.state_recon_beta}
enable_goal_conditioned_action_decoder: false
train_low_level: false                                # true: Train Action Decoder using IL, false: Train Plan Proposal using RL
