defaults:
  - /callbacks/rollout/tasks@tasks: new_playtable_tasks
  - /annotations@val_annotations: new_playtable_validation
_target_: calvin_agent.rollout.rollout_long_horizon_visual_goal.RolloutLongHorizonVisualGoal
_recursive_: false
env_cfg:
  _target_: calvin_agent.wrappers.calvin_env_wrapper.CalvinEnvWrapper
  render_mode: "rgb_array"
skip_epochs: -1 # TODO: change back to 1
rollout_freq: 1
num_videos: 16
num_sequences: 128
replan_freq: 30
ep_len: 360
empty_cache: false
log_video_to_file: false
save_dir: ./videos
lang_folder: notfoundlol #${datamodule.datasets.lang_dataset.lang_folder}
debug: false
