defaults:
  - /callbacks/rollout/tasks@tasks: new_playtable_tasks
_target_: calvin_agent.rollout.rollout_long_horizon_visual_goal.RolloutLongHorizonVisualGoal
_recursive_: false
env_cfg:
  _target_: calvin_agent.wrappers.calvin_env_wrapper.CalvinEnvWrapper
  render_mode: "rgb_array"
skip_epochs: 1
rollout_freq: 5
num_videos: 8
num_sequences: 50
ep_len: 360
empty_cache: false
log_video_to_file: false
save_dir: ./videos
debug: false
start_end_tasks_file: ${oc.env:TAO_DATA_DIR}/calvin_data/start_end_tasks.json
num_tasks_per_rollout: 5 # Chain of 5 tasks as a long-horizon task   
