input_dir: ${oc.env:TAO_DATA_DIR}/calvin/task_D_D
output_dir: ${oc.env:TAO_DATA_DIR}/calvin/task_D_D_rgb64_rot6d_test
desired_keys: ['rel_actions', 'robot_obs', 'scene_obs', 'rgb_static', 'rgb_gripper']  # ['actions', 'rel_actions', 'robot_obs', 'scene_obs', 'rgb_static', 'rgb_gripper', 'rgb_tactile', 'depth_static', 'depth_gripper', 'depth_tactile']
desired_resolution: 64
rgb_interpolation: Area # Area for downsampling, Cubic for upsampling
rot6d: true