defaults:
  - setup
  - ../external/lumos/config/datamodule@datamodule: static_gripper_cam
  - ../external/lumos/config/world_model@world_model: dreamer_v2
  - _self_

exp_dir: ${wm_chk_dir}
wm_chk_dir: /home/nematoli/lumos/logs/runs/2025-07-19/11-59-22/model_weights/last.ckpt  #/path/to/your/model/checkpoint/X.ckpt
output_file: "visionwm_features.pkl"
