defaults:
  - setup
  - logger: wandb
  - ../external/lumos/config/tensor_cores@_global_
  - ../external/lumos/config/callbacks@callbacks: wm_default
  - ../external/lumos/config/datamodule@datamodule: static_gripper_cam
  - ../external/lumos/config/world_model@world_model: dreamer_v2
  - ../external/lumos/config/trainer@trainer: wm_default
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

script: wm
  
hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - datamodule.root_data_dir 