rgb_obs: ['rgb_static', 'rgb_gripper']
depth_obs: ['depth_static', 'depth_gripper']
state_obs: ['robot_obs']
actions: ['rel_actions_gripper'] # actions, rel_actions_world, rel_actions_gripper
language: []
